# Generated by Django 5.0.1 on 2024-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chin',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='des',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ital',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moji',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nor',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sou',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
