# Generated by Django 5.0.1 on 2024-03-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
