# Generated by Django 5.0.1 on 2024-03-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cart1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart1',
        ),
    ]
