# Generated by Django 5.0.1 on 2024-03-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sou'),
        ),
    ]
